### PR TITLE
fix: 423 missing file message

### LINKED ISSUE #423: clearer messages when a referenced file is missing
Earlier today, I was updating some patterns and when I went to run `grit patterns test` hit the following.

```
$ grit patterns test
Error: No such file or directory (os error 2)
```

I did all the usual things thinking this was something I broke in my environment (somehow lost grit) however, that all looked good. After a while, I busted out strace and it turned out this came from grit trying to look up a file in the pattern.

```
$ strace -f -e trace=open,openat ~/.grit/bin/grit patterns test

.. snip

[pid   799] openat(AT_FDCWD, "/mnt/share/.grit/grit.yaml", O_RDONLY|O_CLOEXEC) = 9
[pid   799] openat(AT_FDCWD, "/mnt/share/.grit/../docs/guides/version_5_upgrade.m", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[pid   798] +++ exited with 0 +++
[pid   797] +++ exited with 0 +++
[pid   791] +++ exited with 0 +++
[pid   799] +++ exited with 0 +++
Error: No such file or directory (os error [pid   799] openat(AT_FDCWD, "/mnt/share/.grit/../docs/guides/version_5_upgrade.m", O_RDONLY) = -1 ENOENT (No such file or directory)
2)

.. snip
```

Yep, I did a stupid and removed a trailing letter of the file extension.

To make this easier to debug for others, perhaps wrapping this sort of error up in a nicer handler would be useful? Something like this would be helpful: 

```
$ grit patterns test

Failed to find pattern at "/mnt/share/.grit/../docs/guides/version_5_upgrade.m". Does it exist?
```

### PR DESCRIPTION
**Pull request by Alex-ley-scrub**
/claim #423

- test(patterns_test): add fails_to_find_non_existent_file() test that will fail until the better missing file message is implemented
  - see #423
- fix(parser): add anyhow::Context messages to get_patterns_from_file() awaits if the function fails to find the repo root or fails to read the file path
  - fixes #423

## Greptile Summary

**This is an auto-generated summary**
--
Hi! Looks like you've reached your API usage limit. You can increase it from your account settings page here: [app.greptile.com/settings/usage](https://app.greptile.com/settings/usage)

### CODE REVIEW

File: crates/cli_bin/tests/patterns_test.rs [hunk 1]
```diff
@@ -180,6 +180,32 @@ fn fails_recursion() -> Result<()> {
     Ok(())
 }
 
+#[test]
+fn fails_to_find_non_existent_file() -> Result<()> {
+    let (_temp_dir, temp_fixture_path) = get_fixture("patterns_test", false)?;
+    let test_yaml_path = temp_fixture_path.join(".grit/grit.yaml");
+    // Update it to a config with a non-existent file
```
Comment (morgante) [inline crates/cli_bin/tests/patterns_test.rs:187]: Instead of inline updating please just make a new fixture for this.

**Review by morgante — CHANGES_REQUESTED** [review]
Thanks!

File: crates/cli_bin/tests/patterns_test.rs (hunk 1 above)
Comment (Alex-ley-scrub) [reply crates/cli_bin/tests/patterns_test.rs]: ok no worries, that's done: feb04e4

**Review by morgante — APPROVED** [review]
