### PR TITLE
fix: 416 python hanging comma

### LINKED ISSUE #416: Hanging commas after removing kwargs in Python
Continuing from Discord [message](https://discord.com/channels/1140989670751219762/1140989757392953424/1261006232618143877).

```grit
`TaskMetadata($args)` where {
    $args <: any {
        contains `n_samples=$_` as $ns_kwarg where {
            $ns_kwarg <: `n_samples = $ns_val` => .
        },
        contains keyword_argument(name="avg_character_length") as $avg_kwarg where {
            $avg_kwarg <: `avg_character_length = $avg_val` => `stats=GeneralDescriptiveStats(n_samples=$ns_val, avg_character_length=$avg_val)`
        },
    },
}
```

```python
from pydantic import BaseModel


class TaskMetadata(BaseModel):
    n_samples: dict[str, int]
    avg_character_length: dict[str, float]


if __name__ == "__main__":
    TaskMetadata(
        name="TbilisiCityHallBitextMining",
        dataset={
            "path": "jupyterjazz/tbilisi-city-hall-titles",
            "revision": "798bb599140565cca2dab8473035fa167e5ee602",
        },
        description="Parallel news titles from the Tbilisi City Hall website (https://tbilisi.gov.ge/).",
        type="BitextMining",
        category="s2s",
        eval_splits=[_EVAL_SPLIT],
        eval_langs=_EVAL_LANGS,
        main_score="f1",
        domains=["News"],
        text_creation="created",
        n_samples={_EVAL_SPLIT: 1820},
        reference="https://huggingface.co/datasets/jupyterjazz/tbilisi-city-hall-titles",
        date=("2024-05-02", "2024-05-03"),
        form=["written"],
        task_subtypes=[],
        license="Not specified",
        socioeconomic_status="mixed",
        annotations_creators="derived",
        dialect=[],
        bibtex_citation="",
        avg_character_length={_EVAL_SPLIT: 78},
    )
```

Morgante suggested it might be a bug somewhere around [here](https://github.com/getgrit/gritql/blob/9587e9e5558c583d69514c1f581f8244ac551616/crates/core/src/inline_snippets.rs#L298).

Results in a dangling comma:
image copy

### PR DESCRIPTION
**Pull request by Alex-ley-scrub**
/claim #416
fixes #416 
follows on from PR #419 and uses those test cases but makes the multi line example also work

verified fix with:
```
cargo test --package marzano-core --lib -- --exact --show-output
cargo test --package marzano-core --lib -- test::trailing_comma_after_argument_removal --exact --show-output
cargo test --package marzano-core --lib -- test::trailing_comma_after_argument_removal_one_line --exact --show-output
```

## Greptile Summary

**This is an auto-generated summary**
--
Hi! Looks like you've reached your API usage limit. You can increase it from your account settings page here: [app.greptile.com/settings/usage](https://app.greptile.com/settings/usage)

### CODE REVIEW

File: crates/language/src/python.rs [hunk 1]
```diff
@@ -79,11 +79,22 @@ impl Language for Python {
...
+            if n.text().is_ok_and(|t| t == "->") || n.text().is_ok_and(|t| t == ",") {
                 replacements.push(Replacement::new(n.range(), ""));
             }
             return;
         }
+        if n.node.kind() == "," {
+            // https://github.com/getgrit/gritql/issues/416 multi line example
+            if let Some(prev) = n.node.prev_sibling() {
+                let empty = prev.range().end_byte() == prev.range().start_byte();
+                if prev.kind() == "identifier" && empty {
```
Comment (morgante) [inline crates/language/src/python.rs:92]: Do we need the identifier restriction?

Comment (Alex-ley-scrub) [reply crates/language/src/python.rs]: good point, actually we don't: dcfcf4d0

that also passes all tests locally

I had gone down a few different rabbit holes / routes trying to make this work whilst ensuring all other tests passed as expected - one test that broke with one of my approaches was `test_notebooks::test_insertion` so I was trying to make it pretty strict but actually asserting that the previous node is empty is pretty strict and makes sense for this issue 👌

Comment (morgante) [reply crates/language/src/python.rs]: Perfect, looks like this passes everything. I agree that empty is probably the best check.

**Review by morgante — APPROVED** [review]
