### PR TITLE
fix: 485 allow invalid extensions

### LINKED ISSUE #485: Allow for non-standard suffixes/filenames for languages
I have files that should be treated as python, but do not end in `.py`. I can't convince `grit` to respect the files and treat them as python with any option or config value that I've found. Instead, grit fails with:

```
ERROR (code: 410) - Skipped <mypath here> since it is not a python file
```

My workaround is hardlinking <mypath> to <mypath>.py, but it would be ideal to force grit to ignore the suffix, or to register alternative patterns as a file type using `grit.yaml`.

### PR DESCRIPTION
**Pull request by Alex-ley-scrub**
/claim #485 

fixes #485 

## Greptile Summary

**This is an auto-generated summary**
--
Hi! Looks like you've reached your API usage limit. You can increase it from your account settings page here: [app.greptile.com/settings/usage](https://app.greptile.com/settings/usage)

### CODE REVIEW

**Comment by Alex-ley-scrub** [comment]
The iteration order over the files isn't stable/consistent so I'll need to change my snapshot not to use 3 files at once:
https://github.com/getgrit/gritql/actions/runs/11508722345/job/32037478385?pr=562#step:9:1068

File: crates/cli/src/analyze.rs [hunk 1]
```diff
@@ -205,14 +205,17 @@ where
                 if file.file_type().unwrap().is_dir() {
                     continue;
                 }
+                if my_input.paths.contains(&file.path().to_path_buf()) {
+                    file_paths_tx.send(file.path().to_path_buf()).unwrap();
+                    continue;
```
Comment (morgante) [inline crates/cli/src/analyze.rs:210]: We can't skip https://github.com/getgrit/gritql/pull/562/files#diff-3bdeb1a4ad73fd2fbf7fc4ced8fd6e1413bfcd3c0fa6508706d21fe45e230f6bR255

**Review by morgante — COMMENTED** [review]
Snapshots should usually be of the output files + assert the old error doesn't appear.

File: crates/cli/src/analyze.rs (hunk 1 above)
Comment (Alex-ley-scrub) [reply crates/cli/src/analyze.rs:210]: the new line 209 does the same as 255 (the line you linked)? So we're not skipping it exactly, we're just doing it earlier in a sort of guard clause / early exit style. I can't see what purpose 219-254 serves anymore to be honest - but that's just probably because I don't know the codebase well enough yet.

If we now just always try to parse a path if they explicitly passed it in, then why do we need to check if that file doesn't match the chosen language extension(s)?

Comment (Alex-ley-scrub) [reply crates/cli/src/analyze.rs:210]: > Snapshots should usually be of the output files + assert the old error doesn't appear.

That makes more sense. Updated those: fabe365

Comment (morgante) [reply crates/cli/src/analyze.rs:210]: I'd like to avoid having the same line in 2 places, so try to refactor so we don't have that / line 255 should be the only place we send it.

We do still want to skip cases of non-matching extensions for files that are *not* explicitly passed in, but I think we can drop these lines: https://github.com/getgrit/gritql/pull/562/files#diff-3bdeb1a4ad73fd2fbf7fc4ced8fd6e1413bfcd3c0fa6508706d21fe45e230f6bR220-R252

Comment (Alex-ley-scrub) [reply crates/cli/src/analyze.rs]: done in these 3 commits: https://github.com/getgrit/gritql/pull/562/files/fabe3652a9e5d12d8ed96c5d15e43a9d5025c83c..52d4952cb96beaa8b1b85ed5a0f94157a64dd0ca

**Review by morgante — APPROVED** [review]
Thanks!

**Comment by Alex-ley-scrub** [comment]
@morgante do these bounties get auto awarded once the linked PR merges or not exactly? (This one hasn't yet)

I thought your comment on the issue might automate it but it doesn't seem to have:

https://github.com/getgrit/gritql/issues/485#issuecomment-2436478318

> /assign @Alex-ley-scrub

**Comment by morgante** [comment]
@Alex-ley-scrub No unfortunately I need to manually pay out each bounty.
